# Generated by Django 5.2 on 2025-06-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monumentos', '0002_alter_monumento_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monumento',
            name='documento_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs'),
        ),
        migrations.AddField(
            model_name='monumento',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='cargos'),
        ),
    ]
