# Generated by Django 5.2 on 2025-06-04 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Monumentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaGuiada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=300)),
                ('guia', models.CharField(max_length=100)),
                ('monumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monumentos.monumento')),
            ],
        ),
    ]
