# Generated by Django 5.2 on 2025-06-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaguiada',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
