# Generated by Django 5.2 on 2025-06-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitas', '0002_alter_visitaguiada_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitaguiada',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='cargos'),
        ),
    ]
